services:

  jenkins:
    container_name: jenkins
    image: jenkins-custom
    build:
      context: jenkins
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - ./docker-volumes/jenkins:/var/jenkins_home
    networks:
      - net

  slave:
    container_name: slave
    image: slave-custom
    build:
      context: slave
    networks:
    - net

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin
    ports:
      - "53306:3306"
    volumes:
      - ./mysql-data:/docker-entrypoint-initdb.d
    networks:
      - net

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: 'gitlab.example.com'
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#         Add any other gitlab.rb configuration here, each on its own line
#        external_url 'https://gitlab.example.com'
    ports:
      - '5080:80'
#      - '50443:443'
#      - '5022:22'
    volumes:
      - './docker-volumes/gitlab/config:/etc/gitlab'
      - './docker-volumes/gitlab/logs:/var/log/gitlab'
      - './docker-volumes/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - net

networks:
  net:
