services:

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - ./docker-volumes/jenkins:/var/jenkins_home
    networks:
      - net

  slave:
    container_name: slave
    image: slave
    build:
      context: slave
    networks:
    - net

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin
    ports:
      - "53306:3306"
    volumes:
      - ./mysql-data:/docker-entrypoint-initdb.d
    networks:
      - net

networks:
  net:
