name: Concatenate strings

description: Description of the action

runs:
  using: composite
  steps:
    - id: f1
      name: Print date
      shell: bash
      run: echo 'date'
    - id: f2
      name: Print env
      shell: bash
      run: printenv
