name: Concatenate strings

description: Description of the action

inputs:
  sraka:
    description: 'SRAKA'
    required: false
    default: 'SRAKA1'

runs:
  using: composite
  steps:
    - id: f1
      name: Print date
      shell: bash
      run: echo 'date'
    - id: f2
      name: Print env
      shell: bash
      run: printenv
    - id: f3
      name: Print input
      shell: bash
      run: echo "sraka is the next - ${{ inputs.sraka }}"
