name: reusable

on:
  workflow_call:
    inputs:
      sraka:
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: St1
        run: echo 1
      - name: St1
        run: echo 1
  job2:
    runs-on: ubuntu-latest
    needs: [ "job1" ]
    steps:
      - name: Ending activities
        run: echo "end"
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Ending activities
        run: echo ${{ inputs.sraka }}
