name: test-context-output

on: workflow_dispatch

jobs:
  init1:
    needs: [ "init2", "execute" ]
    runs-on: ubuntu-latest
    steps:
      - name: print 'github' props
        run: echo "${{ toJSON(github.job) }}"

  init2:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.set-should-run.outputs.shouldrun}}
    steps:
      - name: print 'github' props
        id: set-should-run
        run: echo "shouldrun=true" >> $GITHUB_OUTPUT

  execute:
    needs: init2
    runs-on: ubuntu-latest
    if: ${{ needs.init2.outputs.should_run == 'true' }}
    steps:
      - name: execute request
        run: echo "execute request"
