name: test-context-output2

on: workflow_dispatch

jobs:

  init:
    runs-on: ubuntu-latest
    steps:
      - name: st1
        run: |
          echo variable: ${{ vars.REPO_VAR1 }}
      - name: st2
        run: |
          echo secret: ${{ vars.REPO_SECRET1 }}
